dataset_path: data/dataset_v4.csv
target_column: MedHouseVal

model: [linear, random_forest, gradient_boosting]

model_params:
  linear:
    fit_intercept: true

  random_forest:
    n_estimators: 100
    max_depth: 5
    random_state: 42

  gradient_boosting:
    learning_rate: 0.1
    n_estimators: 100
    max_depth: 3
    random_state: 42

automl:
  models:
    - name: DecisionTree
      max_depth: 5
    - name: RandomForest
      n_estimators: 100
      max_depth: 10
    - name: GradientBoosting
      learning_rate: 0.1
      n_estimators: 50
